### ISSUE TITLE
http scheme in invite

### ISSUE THREAD

**Issue by IlyaBat9** [rabochyee-nazvanye/quest-frontend#45]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/7255833/80260222-d682b100-86a0-11ea-808b-b786e00a95e2.png">
При копировании инвайта сокомандникам не все мессенджеры воспринимают questspace.live/invites/NCQWOV как сайт. Из-за этого ссылка некликабельна.

**Comment by IlyaBat9** [comment]
Поиграйте со мной?

**Comment by tramakarov** [comment]
Добавили https:\\ к инвайт-ссылкам

**Comment by IlyaBat9** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/7255833/80286619-edc7aa00-8745-11ea-950e-addec8207ae6.png">

**Comment by IlyaBat9** [comment]
Поиграйте со мной?
