### ISSUE TITLE
Problems with registration form

### ISSUE THREAD

**Issue by tramakarov** [rabochyee-nazvanye/quest-frontend#72]
При нажатии на «или зарегистрироваться» в форме авторизации вылетает ошибка

**Comment by toplenboren** [comment]
Проверил на `dev` на 5/30/2020 9:10 PM в Мозилле и в Хроме, ни разу не получилось уронить. 

https://www.loom.com/share/855c362e156f410d81c7866a3d5914b5

Нужно как-то более детально. Запиши лум?

**Comment by tramakarov** [comment]
Поправил редьюсер, был кривой копипаст, который затронул уже реализованную часть
